---
- hosts: all
  remote_user: "{{user}}"
  vars:
    target_path: /tmp
    user: "{{user}}"
  tasks:
    - name: copy soft
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
      with_items:
        - {
            src: "tmp_script",
            dest: "{{target_path}}/",
            owner: "heals",
            group: "heals",
            mode: "0755",
          }

    - name: exec script
      shell: /tmp/tmp_script

