# Generated by Django 3.1.7 on 2022-03-07 17:50

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0003_auto_20220307_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='维基类型', max_length=50, verbose_name='维基类型')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '维基类型',
                'verbose_name_plural': '维基类型',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='标题', max_length=50, verbose_name='标题')),
                ('content', ckeditor.fields.RichTextField(verbose_name='内容')),
                ('number', models.IntegerField(default=0, help_text='阅读次数', verbose_name='阅读次数')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='member.user', verbose_name='作者')),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='wiki.category', verbose_name='类目')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-c_time'],
            },
        ),
    ]
