# Generated by Django 3.1.7 on 2022-03-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-c_time'], 'verbose_name': '类目', 'verbose_name_plural': '类目'},
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(help_text='类目', max_length=50, verbose_name='类目'),
        ),
    ]
