# Generated by Django 3.1.7 on 2022-03-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='姓名', max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='', max_length=32, verbose_name='性别')),
                ('phone', models.CharField(help_text='电话', max_length=50, unique=True, verbose_name='电话')),
                ('email', models.CharField(help_text='邮箱', max_length=50, verbose_name='邮箱')),
                ('password', models.CharField(help_text='密码', max_length=50, verbose_name='密码')),
                ('icon', models.ImageField(default='icon/default.jpg', upload_to='icon')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '姓名',
                'verbose_name_plural': '员工信息',
                'ordering': ['-c_time'],
            },
        ),
    ]
