# Generated by Django 3.1.7 on 2022-03-07 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff',
            new_name='User',
        ),
    ]
