# Generated by Django 3.1.7 on 2022-03-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20220307_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='名称', max_length=50, verbose_name='名称')),
                ('username', models.CharField(help_text='用户名', max_length=50, verbose_name='用户名')),
                ('password', models.CharField(blank=True, help_text='密码', max_length=50, verbose_name='密码')),
                ('sshkey', models.FileField(default='', upload_to='sshkey')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '名称',
                'verbose_name_plural': '执行用户',
                'ordering': ['-c_time'],
            },
        ),
    ]
