# Generated by Django 3.1.7 on 2022-03-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_execuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execuser',
            name='sshkey',
            field=models.FileField(blank=True, default='', upload_to='sshkey'),
        ),
    ]
