# Generated by Django 3.1.7 on 2022-03-11 10:12

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='通知标题', max_length=50, verbose_name='通知标题')),
                ('content', mdeditor.fields.MDTextField(verbose_name='内容')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '系统通知',
                'verbose_name_plural': '系统通知',
                'ordering': ['-c_time'],
                'get_latest_by': 'c_time',
            },
        ),
        migrations.RemoveField(
            model_name='message',
            name='type',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
