# Generated by Django 3.1.7 on 2022-03-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='站点名称', max_length=50, verbose_name='站点名称')),
                ('url', models.CharField(help_text='地址', max_length=50, verbose_name='地址')),
                ('description', models.TextField(blank=True, default='站点描述', max_length=256, verbose_name='站点描述')),
                ('logo', models.ImageField(default='', upload_to='icon')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '站点',
                'verbose_name_plural': '站点',
                'ordering': ['-c_time'],
            },
        ),
    ]
