# Generated by Django 3.1.7 on 2022-03-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='env',
            field=models.CharField(choices=[('prod', '正式环境'), ('exp', 'example环境'), ('test', '测试环境'), ('dev', '开发环境')], default='', max_length=32, verbose_name='环境信息'),
        ),
    ]
