# Generated by Django 3.1.7 on 2022-03-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_site_env'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='doc',
            field=models.CharField(default='', help_text='文档地址', max_length=50, verbose_name='文档地址'),
        ),
        migrations.AddField(
            model_name='site',
            name='github',
            field=models.CharField(default='', help_text='源码地址', max_length=50, verbose_name='源码地址'),
        ),
        migrations.AlterField(
            model_name='site',
            name='description',
            field=models.TextField(blank=True, default='', max_length=256, verbose_name='站点描述'),
        ),
    ]
