# Generated by Django 3.1.7 on 2022-03-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='是否在线'),
        ),
        migrations.AddField(
            model_name='server',
            name='os',
            field=models.CharField(blank=True, help_text='操作系统', max_length=50, verbose_name='操作系统'),
        ),
    ]
