# Generated by Django 3.1.7 on 2022-03-09 13:36

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0005_auto_20220308_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='语言', max_length=50, verbose_name='语言')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '语言',
                'verbose_name_plural': '语言',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(help_text='别名', max_length=50, verbose_name='别名')),
                ('name', models.CharField(help_text='名称', max_length=50, verbose_name='名称')),
                ('content', mdeditor.fields.MDTextField(verbose_name='内容')),
                ('note', models.CharField(help_text='备注', max_length=50, verbose_name='备注')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='member.user', verbose_name='作者')),
                ('language', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='script.language', verbose_name='语言')),
            ],
            options={
                'verbose_name': '脚本',
                'verbose_name_plural': '脚本',
                'ordering': ['-c_time'],
            },
        ),
    ]
