# Generated by Django 3.1.7 on 2022-03-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='note',
            field=models.CharField(blank=True, help_text='备注', max_length=50, verbose_name='备注'),
        ),
    ]
