# Generated by Django 3.1.7 on 2022-03-10 17:05

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0005_auto_20220308_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='配置类型', max_length=50, verbose_name='配置类型')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '配置类型',
                'verbose_name_plural': '配置类型',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='Conf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(help_text='别名', max_length=50, verbose_name='别名')),
                ('name', models.CharField(help_text='名称', max_length=50, verbose_name='名称')),
                ('content', mdeditor.fields.MDTextField(verbose_name='内容')),
                ('note', models.CharField(blank=True, help_text='备注', max_length=50, verbose_name='备注')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='member.user', verbose_name='作者')),
                ('type', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='conf.type', verbose_name='类型')),
            ],
            options={
                'verbose_name': '配置文件',
                'verbose_name_plural': '配置文件',
                'ordering': ['-c_time'],
            },
        ),
    ]
