# Generated by Django 3.1.7 on 2022-03-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='extension',
            field=models.CharField(blank=True, help_text='后缀名', max_length=50, verbose_name='后缀名'),
        ),
    ]
