# Generated by Django 3.1.7 on 2022-03-16 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0005_auto_20220308_1641'),
        ('conf', '0001_initial'),
        ('script', '0002_auto_20220309_1449'),
        ('property', '0002_auto_20220308_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='名称', max_length=50, unique=True, verbose_name='名称')),
                ('type', models.CharField(choices=[('interval', 'interval'), ('cron', 'cron')], default='', max_length=32, verbose_name='类型')),
                ('day_of_week', models.CharField(blank=True, help_text='重复日期', max_length=50, verbose_name='重复日期')),
                ('hour', models.CharField(blank=True, help_text='小时', max_length=50, verbose_name='小时')),
                ('minute', models.CharField(blank=True, help_text='分钟', max_length=50, verbose_name='分钟')),
                ('second', models.CharField(blank=True, help_text='秒', max_length=50, verbose_name='秒')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('playbook', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='conf.conf', verbose_name='执行剧本')),
                ('script', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='script.script', verbose_name='执行脚本')),
                ('servers', models.ManyToManyField(default='', to='property.Server', verbose_name='执行服务器')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='member.execuser', verbose_name='执行用户')),
            ],
            options={
                'verbose_name': '定时任务',
                'verbose_name_plural': '定时任务',
                'ordering': ['-c_time'],
            },
        ),
    ]
