# Generated by Django 3.1.7 on 2022-03-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crontask',
            name='is_load',
            field=models.BooleanField(default=False, verbose_name='是否加载'),
        ),
    ]
